from .registry import ToolRegistry
from .filesystem import (
    filesystem_list,
    filesystem_list_detailed,
    filesystem_search,
    filesystem_read,
    filesystem_write,
    filesystem_create_directory,
    filesystem_delete,
    filesystem_copy,
    filesystem_move,
    filesystem_view_lines,
    filesystem_find_in_files,
    filesystem_replace_content,
    filesystem_set_workspace,
    filesystem_get_workspace,
)
from .applications import (
    applications_list,
    applications_open,
    applications_is_running,
    applications_close,
)
from .screenshot import screenshot_take
from .browser import (
    browser_open,
    browser_search,
    browser_youtube_search,
    browser_play_video,
    browser_click_first_result,
    browser_click_link,
)
from .system import system_info, system_resources, processes_list, processes_find
from .terminal import terminal_run
from .git import (
    git_status,
    git_diff,
    git_log,
    git_commit,
    git_branch,
    git_checkout,
    git_switch,
    git_pull,
    git_push,
    git_info,
    git_safe_rollback,
)
from .desktop import (
    mouse_move,
    mouse_click,
    mouse_double_click,
    mouse_scroll,
    mouse_get_position,
    keyboard_type,
    keyboard_press,
    keyboard_hotkey,
    desktop_get_windows,
    desktop_get_active_window,
    desktop_switch_window,
    desktop_close_window,
    desktop_inspect_screen,
    screenshot_analyze,
    safety_reset,
)

__all__ = [
    "ToolRegistry",
    "filesystem_list",
    "filesystem_list_detailed",
    "filesystem_search",
    "filesystem_read",
    "filesystem_write",
    "filesystem_create_directory",
    "filesystem_delete",
    "filesystem_copy",
    "filesystem_move",
    "filesystem_view_lines",
    "filesystem_find_in_files",
    "filesystem_replace_content",
    "filesystem_set_workspace",
    "filesystem_get_workspace",
    "applications_list",
    "applications_open",
    "applications_is_running",
    "applications_close",
    "screenshot_take",
    "screenshot_analyze",
    "browser_open",
    "browser_search",
    "browser_youtube_search",
    "browser_play_video",
    "browser_click_first_result",
    "browser_click_link",
    "system_info",
    "system_resources",
    "processes_list",
    "processes_find",
    "terminal_run",
    "git_status",
    "git_diff",
    "git_log",
    "git_commit",
    "git_branch",
    "git_checkout",
    "git_switch",
    "git_pull",
    "git_push",
    "git_info",
    "git_safe_rollback",
    "mouse_move",
    "mouse_click",
    "mouse_double_click",
    "mouse_scroll",
    "mouse_get_position",
    "keyboard_type",
    "keyboard_press",
    "keyboard_hotkey",
    "desktop_get_windows",
    "desktop_get_active_window",
    "desktop_switch_window",
    "desktop_close_window",
    "desktop_inspect_screen",
    "safety_reset",
]

